### ISSUE TITLE
Charm break does not wipe hatelists

### ISSUE THREAD

**Issue by GangstaEQ** [EQEmu/Server#1359]
When charm breaks the mob that was previously charmed should be wiped from any other mob’s hatelist. Currently if a mob breaks free from charm they will still be attacked by mobs as if it were still charmed. IE the mob retains its position on the hatelist, this can be exploited to start faction wars.

**Comment by dencelle** [comment]
iirc this is actually live like as it is currently, i remember playing an enchanter and i'd go to freeport and do this exact thing to cause GMs to start fight with other GMs since they weren't along the same faction (yes, it did cause exploit issues, but it was live like so not sure if this really counts as a bug)
