### ISSUE TITLE
[Bots] Heal rotations are lost during zoning

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#3547]
When zoning, heal rotations are lost or deleted. 

OS: Debian 12
EQEmu: main CURRENT_VERSION [22.24.0-dev]

Steps to reproduce:

- spawn a warrior bot
- spawn a cleric bot
- target the cleric bot and create a heal rotation
- add the warrior bot to heal rotation
- save the heal rotation
- list the heal rotation to confirm it exists
- start and stop the heal rotation to check no errors
- zone
- spawn the cleric and warrior bots again
- list the heal rotation again - doesn't exist

Checked server console and no errors are observed.

![HealrotationZone](https://github.com/EQEmu/Server/assets/95503076/85c2e39b-f09a-4aaa-abe0-4081e9574789)

**Comment by fryguy503** [comment]
That is because it is stored in memory at the zone level. I am betting if you set a different rotation in the 2nd zone then zone back to the first it would revert to what you had in the first zone.

**Comment by nytmyr** [comment]
Trust is correct.

When you zone you have to reload the HR. Save it as needed, then every time you zone respawn all required bots for the HR and do ^hrcreate on the HR leader and it'll load the HR. Unless it was fixed, hrload didn't typically work properly but hrcreate will reload a saved HR.

**Comment by khinch** [comment]
Looking at the data tables there is no zone data associated with the heal rotations. So what you're saying is the zone loads the heal rotations as you enter the zone, and if those bots are not spawned then it just doesn't load the rotation? Does this mean if I add the bots to a raid when I zone the HR will persist? Or does adding them to a raid just automatically spawn them after the zone loads? 

Is there a reason the zone can't load the HR when you first perform a HR action, like list/start etc?

**Comment by nytmyr** [comment]
> Looking at the data tables there is no zone data associated with the heal rotations. So what you're saying is the zone loads the heal rotations as you enter the zone, and if those bots are not spawned then it just doesn't load the rotation? Does this mean if I add the bots to a raid when I zone the HR will persist? Or does adding them to a raid just automatically spawn them after the zone loads?
> 
> Is there a reason the zone can't load the HR when you first perform a HR action, like list/start etc?

HRs are saved to the database but they are only loaded in the zone you commanded them to be loaded. They don't persist across zones.

It could be done but in their current state isn't really feasible because the HR relies on its assigned bots to be spawned at HR load, it won't add them back to the HR if the HR was preloaded and then they were spawned after.

Example of how an HR is created/activated.

Spawn all the bots you want to be affected by an HR, create HR on leader, customize HR, save HR.

Then on zone, bots are technically camped at zone out and then respawned upon zoning in, so if the HR was already loaded to persisted across the zone, any bots loaded after the HR would be missing from the HR. So HR would be needed to loaded last after the bots are spawned (in HRs current form)
