### ISSUE TITLE
[Bug] Translocator Kurione in Iceclad TPs Character to Wrong Zone

### ISSUE THREAD

**Issue by brickbuckett** [EQEmu/Server#3775]
While testing the translocators between Northern Ro and Iceclad, Translocator Kurione will TP characters to the wrong version of Northern Ro. Likely expecting nro (34) rather than northro (392).

**Zone Debug - Iceclad Log**
`[Debug] Zone [iceclad] Player [Erudench] has requested a zoning to LOC x=[-2626], y=[6055], z=[6], heading=[130] in zoneid=[392]`
```
{
  "from_zone_long_name": "The Iceclad Ocean",
  "from_zone_short_name": "iceclad",
  "from_zone_id": "110",
  "from_instance_id": "0",
  "from_instance_version": "0",
  "to_zone_long_name": "North Desert of Ro",
  "to_zone_short_name": "northro",
  "to_zone_id": "392"
  "to_instance_id": "0"
  "to_instance_version": "0",
}
```
**Client Crashes w/ Error**
![image](https://github.com/EQEmu/Server/assets/3444470/fc7abf72-e8ed-4423-bbac-c5a147e68ee4)
**Client Information**
- Clean install of Titanium
- Patched with http://www.projecteq.net/forums/index.php?threads/dragons-of-norrath-release.17601/

**Comment by fryguy503** [comment]
This is due to the spell being from live, you can either hard code the quest or update the spell.

Spell Data: https://lucy.allakhazam.com/spellhistory.html?id=2282&source=Live

You can see in 2006 when PoR released it was updated:


2006-10-05 07:37 | Changed Slot 1 from "Teleport to 783,-864,0.14 in nro facing SE" to "Teleport to 6055,-2626,6 in northro facing South"
