### ISSUE TITLE
If a task is completed more than once and rule KeepOneRecordPerCompletedTask is true - the task is completely erased from db

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#4247]
Do a task once.

Its in the completed_task db.

Do it again, with the rule KeepOneRecordPerCompletedTask  set to true.

Task is no longer shown as completed.

Is this a feature so IsCompleted() works in quests or a bug?  Our wiki shows those that complete tasks and when they do it a second time it is erased.

**Comment by hgtw** [comment]
It's a bug, changing
https://github.com/EQEmu/Server/blob/b1d873d1fcf77300f218f0377a9b950108dbdaa2/zone/task_client_state.cpp#L422
to

`size_t erased = before - m_completed_tasks.size();`
should fix it

**Comment by noudess** [comment]
> It's a bug, changing
> 
> https://github.com/EQEmu/Server/blob/b1d873d1fcf77300f218f0377a9b950108dbdaa2/zone/task_client_state.cpp#L422
> 
> 
> to
> `size_t erased = before - m_completed_tasks.size();` should fix it

How?  Wont that prevent the deletion of the old one?  I thought the intent is to delete the old one so there are not two?

**Comment by hgtw** [comment]
`before` should be greater than `m_completed_tasks.size()` after the erase, so currently `erased` will underflow and cause `m_last_completed_task_loaded` to increment instead of decrement after sign conversions. This prevents the db replace in `SaveClientState` because it's now bigger than `m_completed_tasks.size`. I assume the task code is just using that variable as a dirty flag for a db update.

**Comment by noudess** [comment]
You ok with PRing this since you clearly have a better grasp?

**Comment by hgtw** [comment]
Feel free, it needs confirmation anyway
