### ISSUE TITLE
Modern AA XP Bonus

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#656]
Modern EQ has an AA XP mod based on how many AAs you have. I'm not 100% sure when this was added and I lost the exact dev quotes

at 4000 AAs this bonus is gone. At 0 AAs it is 1000%. The rate is from a look up table, but the devs described it as basically linear (probably just more steppy than actually linear, maybe every 5 levels are the same?)

If we implement this we could probably just do straight linear, it will be fairly accurate to what live does. We would also be able to easily set up a few rules to customize this in a fairly obvious way.

**Comment by daerath** [comment]
I'll take a look at this one.  I'm thinking that the scaling bonus 10x at 0 AA linearly scaling to 1x at 4000 AA (so, no bonus) would come after all other XP bonuses (e.g. racial modifiers, hot zone modifiers, etc.).

Rules to control this could be:
Character:UseModernAAExperienceScale (true/false) -- To use the new scale system or the old one
Character:ModernAAScalingAAMinimum (0) -- The number of AA where XP scaling begins.
Character:ModernAAScalingAALimit (4000) -- The number of AA where XP scaling ends.
Character:ModernAAScalingStartPercent (1000) -- Base percentage that applies upon reaching the AA Minimum value.

**Comment by daerath** [comment]
Change occurred sometime during the week of Feb 15th 2008, here is the text I've found.

One of the most common topics of discussion on these boards has to do with AAs - gaining them, using them and how many you "need" to be viable in a group or raid setting. As time passes and expansions are released the total number of AAs that are available to each class grows, as does the number of AAs that are considered "core" by each class. Anyone who has played EverQuest for very long can realize how important a few hundred well-spent AA can be for any player of sufficient level. As great as the AA system is, however, it presents an ever growing barrier to new players or current players who might like to try a new class for a different experience or perspective. The hill, to put it simply, is simply too high to climb for many people.
 
To address this we're going to introduce the same type of experience scaling in the AA system that exists with levels. Just like level 1 is a lot easier to get than level 80 is we're going to change how AA experience works so that the first AAs you earn will come faster than the last AA you earn to reach the cap. This change should make it a lot easier for players climbing the levels to gain key AAs and advance to the point that they can interact with friends (new or old) that have more established characters.
 
What we've done is put together a very flexible, data-driven system that we can adjust as expansions are released or in response to changing circumstances. The way the system works is that we'll be able to create point ranges (with a minimum number of AAs earned and a maximum number) that will have a multiplier assigned to it. So you'll get the amount of experience you would have gotten prior to this change, but then that experience is increased by this multiplier.
 
So for AA #XYZ your multiplier might be 2.0. Before the change you would have gotten 500 experience. After the change it would be 500 x 2, or 1000 experience. Simple, right?
 
The higher you go in AA totals the lower the multiplier will be until eventually it will reach the 1.0 mark and AA experience will return to "normal". AA experience is already normalized by level to be equal to the same number of even-con kills no matter what your level is and this system will work with that. No matter where you are in terms of level you'll see the same bonus based on your AA count.
 
Based on the data we collected a few months ago and looking at where we're putting the 1.0 mark the vast majority of players will see a boost in the rate that they earn AAs with those at the low end of the AA count seeing the largest boost. As I mentioned above we're able to nimbly change the shape of the curve and as we release new expansions that push forward the total number of AAs that exist we will be changing the shape of the curve, including the point where AA experience returns to normal. So we'll be attempting to continue to support new players and returning veterans going forward with the AA system.

**Comment by mackal** [comment]
Yeah, I think our AA formulas may even need some work ... at least for the early TSS changes that took place, but I'm not 100% sure :P

This should also probably be default off since most servers are in an era where this maybe a bit OP

**Comment by daerath** [comment]
Yup, setting it off by default.  I think I'll add these changes first and then take a look at the AA rate in general.  My initial testing shows that it is a pretty crazy boost in AA XP, although with the scaling settings the bonus could easily be changed to be a lower value or a smaller range.  I'm also writing it so that it doesn't have to start at 0 AA.  You could just as easily customize it to start at 500 AA or some other value.

**Comment by daerath** [comment]
So my thoughts on the TSS changes -- the bit about each AA being the same # of white con mobs regardless of your level or total # of AAs.  That should be pretty simple.

The current G, LB, B, W, Y, R modifiers we use are: 20, 40, 90, 100, 125, 150

So what we can do for AA XP is to continue using the current XP per AA total (any value would work, but leaving it alone is simpler) and then make the below calculation.  The color modifiers are being used to adjust the kills per AA based on the con.  It was simpler to use those than to make up something new.

AA XP per kill = AAPerXP / (WhiteKillsPerAA / (ColorModifier/100))

So for the current XP per AA (23976503) that translates to the below kills per AA:
Green: 50
Light Blue: 25
Blue: 11
White: 10 (which matches the TSS changes)
Yellow: 8
Red: 6 (or 7 if we're rounding up)

**Comment by mackal** [comment]
http://www.tski.co.jp/baldio/patch/20060919.html

That's the AA changes for TSS (that's like the first TSS patch)

**Comment by daerath** [comment]
Good deal.  So it's actually whatever a 70th level character needed to get 1 AA.  I can't find that value, but I am basing the formula off the XP per AA rule, so that's consistent even if we don't know the value.

**Comment by mackal** [comment]
Note: I have no idea if what we do is correct :P

**Comment by daerath** [comment]
With this code merged, can this issue be closed?  Thank you!
